#!/usr/bin/env bash

nva_version="1.3.0"

# Get the directory of the script, resolving symbolic links
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

node_versions_dir="$script_dir/nodejs"
cleanup="false"

install_version=""
set_version=""
remove_version=""
all_versions=$(curl -s https://nodejs.org/download/release/ | grep -oP '^<a href="v\K\d+\.\d+\.\d+' | uniq | sort -V)

if [ ! -d "$node_versions_dir" ]; then
    if [ -w "$script_dir" ]; then
        mkdir "$node_versions_dir"
    else
        echo "Error: Permission Denied"
        echo "You don't have the necessary permissions to create the 'nodejs' directory in $script_dir."
        echo "Please run the command with sudo: sudo nva"
        exit 1
    fi
fi

check_running_node_version(){
    if [ -n "$(command -v node)" ]; then
        running_version=$(node --version | grep -oP '\d.*')
    fi
}

print_help() {
    cat <<EOF
nva - Node Version Admin (Version $nva_version)

Usage: nva [OPTIONS]

Options:
  -i, --install        Install a specific Node.js version

  -l, --list           List available Node.js versions on your system

  -s, --set            Set the active Node.js version

  -p, --patch          Update all installed Node.js versions to the latest patch.
                       This automatically removes old versions and updates the patch number.

  -r, --remove         Remove an installed Node.js version

  -v, --version        Print the version of nva

  -h, --help           Display this help message and exit

EOF
}

print_version() {
    echo "nva - Node Version Admin (Version $nva_version)"
}

install() {
    if [ -e "$node_versions_dir/$install_version" ]; then
        echo "Node.js version $install_version is already installed on your system."
    else
        if [ -w "$node_versions_dir" ]; then
            local response_code=$(curl -sLI "https://nodejs.org/download/release/v$install_version/" | grep -i "^HTTP" | awk '{print $2}')
            if [ $? -ne 0 ] || [ -z "$response_code" ]; then
                echo "Error -i|--install: no connection to https://nodejs.org/download/release/"
                exit 1
            fi
            if [ "$response_code" -eq 200 ]; then
                curl -sL "https://nodejs.org/download/release/v$install_version/node-v$install_version-linux-x64.tar.xz" -o "$node_versions_dir/node-v$install_version-linux-x64.tar.xz"
                if [ $? -eq 0 ]; then
                    echo "Node.js version $install_version downloaded successfully to $node_versions_dir"

                    mkdir "$node_versions_dir/$install_version"

                    tar -xf "$node_versions_dir/node-v$install_version-linux-x64.tar.xz" -C "$node_versions_dir/$install_version" --strip-components=1

                    if [ $? -eq 0 ]; then
                        echo "Node.js version $install_version extracted successfully"
                        rm -r "$node_versions_dir/node-v$install_version-linux-x64.tar.xz"
                    else
                        echo "-i|--install Failed to extract Node.js version $install_version"
                        exit 1
                    fi
                else
                    echo "-i|--install Failed to download Node.js version $install_version"
                    exit 1
                fi
            else 
                echo "-i|--install The version $install_version doesn't exist"
                exit 1
            fi
        else
            echo "Error -i|--install: You don't have permission"
            exit 1
        fi
    fi
}

list(){
    check_running_node_version
    local local_versions=$(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | grep -oP '\d+(\.\d+){0,2}')
    if [ -n "$local_versions" ]; then
    echo "Available Node.js versions installed on your system:"
    for version in $local_versions; do
            if [ "$running_version" = "$version" ]; then
                echo "* Node.js $version (Running)"
            else
                echo "  Node.js $version"
            fi
        done
    else
        echo "No Node.js versions found in $node_versions_dir."
        echo "You may want to install Node.js using the nva script."
        echo -e "nva --install <node_version>\n"
        exit 1
    fi

}

set_nodejs(){
    if [ -n "$set_version" ] && [ -e "$node_versions_dir/$set_version" ]; then
        if [ "$(id -u)" -eq 0 ]; then
            ln -srf "$node_versions_dir/$set_version/bin/node" /usr/bin/node
            ln -srf "$node_versions_dir/$set_version/bin/npx" /usr/bin/npx
            ln -srf "$node_versions_dir/$set_version/bin/npm" /usr/bin/npm
            npm config set prefix /usr/local -g
            echo "Node.js version $set_version has been set successfully."
        else
            echo "Error -s|--set: Insufficient privileges. Please run with sudo."
            exit 1
        fi
    else
        echo "Error -s|--set: Node.js version $set_version does not exist in your system."
        exit 1
    fi
}

remove() {
    check_running_node_version

    # If wildcard is used
    if [[ "$remove_version" == *"*"* ]]; then
        local matches=($(find "$node_versions_dir" -maxdepth 1 -type d -printf '%f\n' | grep -E "^${remove_version//\*/.*}$"))
        
        if [ ${#matches[@]} -eq 0 ]; then
            echo "Error -r|--remove: No versions match the pattern '$remove_version'."
            exit 1
        fi

        for match in "${matches[@]}"; do
            if [ "$match" == "$running_version" ]; then
                echo "Skipping currently running version: $match"
                continue
            fi

            if [ -w "$node_versions_dir/$match" ]; then
                rm -rf "$node_versions_dir/$match"
                echo "Removed: $match"
            else
                echo "Error -r|--remove: No permission to remove $match"
            fi
        done
        return
    fi

    # If exact version is given
    if [ -e "$node_versions_dir/$remove_version" ]; then
        if [ "$remove_version" != "$running_version" ]; then
            if [ -w "$node_versions_dir/$remove_version" ]; then
                rm -rf "$node_versions_dir/$remove_version"
                echo "Node.js version $remove_version has been removed."
            else
                echo "Error -r|--remove: You do not have permission to remove Node.js version $remove_version."
                echo "Check file permissions and try again or run with elevated privileges."
            fi
        else
            echo "Info: Cannot remove the currently running Node.js version."
            echo "Use 'nva --set <node_version>' to set another version before removing the running version."
        fi
    else
        echo "Error -r|--remove: The specified Node.js version ($remove_version) does not exist."
        exit 1
    fi
}

# Update the version patch in the format MAJOR.MINOR.PATCH so that only the patch number is updated for example, from 24.4.0 to 24.4.1
patch(){
    check_running_node_version
    echo "#### Running Patch ####"
    if [ $? -ne 0 ] || [ -z "$all_versions" ]; then
        echo "Error -p|--patch: no connection or failed to fetch versions"
        exit 1
    fi

    local installed_versions=($(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;))
    for version in "${installed_versions[@]}"; do
        local strip_version=$(echo "$version" | grep -oP '^\d+\.\d+')
        local check_patch_version=$(echo "$all_versions" | tr ' ' '\n' | grep -oP "^${strip_version}\.\d+" | tail -n 1)
        if [ "$version" != "$check_patch_version" ]; then
            echo "Need update: $version → $check_patch_version"
            install_version=$check_patch_version
            install
            if [ $? -ne 1 ]; then
                if [ "$version" == "$running_version" ]; then
                    set_version=$check_patch_version
                    set_nodejs
                fi
                remove_version=$version
                remove
            fi
        fi
    done
}


if [ $# -eq 0 ]; then
    print_help
    exit 0
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -i|--install)
            if [ -n "$2" ]; then
                if [ "$2" = "latest" ]; then
                    install_version=$(echo "$all_versions" | tail -n 1)
                else 
                    install_version="$2"
                fi 
                install
                shift 2
            else
                echo "Error: -i/--install option requires a version parameter"
                exit 2
            fi
            ;;
        -s|--set)
            if [ -n "$2" ]; then
                if [ "$2" = "latest" ]; then
                        set_version=$(echo "$all_versions" | tail -n 1)
                    else 
                        set_version="$2"
                fi 
                set_nodejs
                shift 2
            else
                echo "Error: -s/--set option requires a version parameter"
                exit 2
            fi
            ;;
        -r|--remove)
            if [ -n "$2" ]; then
                remove_version="$2"
                remove
                shift 2
            else
                echo "Error: -r/--remove option requires a version parameter"
                exit 2
            fi
            ;;
        -l|--list)
            list
            shift
            ;;
        -p|--patch)
            patch
            shift
            ;;
        -v|--version)
            print_version
            exit 0
            ;;
        -h|--help)
            print_help
            exit 0
            ;;
        *)
            echo "Error: Unknown option '$1'"
            print_help
            exit 1
            ;;
    esac
done

